package com.loanservice.domain;
public enum RejectionReason { AGE_OUT_OF_RANGE, CREDIT_SCORE_OUT_OF_RANGE, LOAN_AMOUNT_OUT_OF_RANGE, TENURE_OUT_OF_RANGE, MONTHLY_INCOME_ZERO_OR_LESS, CREDIT_SCORE_TOO_LOW, AGE_TENURE_LIMIT_EXCEEDED, EMI_EXCEEDS_60_PERCENT, EMI_EXCEEDS_50_PERCENT }
